
version: '3.1'

services:

  web-server:
    image: php:7.2-apache
    restart: always
    container_name: sv    
    ports:
      - 8072:80
    volumes:
      - ./trim/:/var/www/html
    networks:
      - net2

networks:
  net2:
    driver: bridge

